### PR TITLE
A few minor edits

### PR DESCRIPTION
**Pull request by martinthomson**
Just some editorial stuff.  Compare with -w if you think that it looks like a lot of changes.

### CODE REVIEW

**Comment by martinthomson** [comment]
Ugh, bad setup made this fail first time around.

**Comment by yoavnir** [comment]
Oops. I hadn't noticed your PR when I changed the reference of CFRG-Curves to RFC7748. Now there's a conflict. Sorry about that.

The changes look fine and don't look like they need discussion, but what is "Verson is important now"?

**Comment by martinthomson** [comment]
Bad timing. You can see the changes in the commit by selecting just the commit.

**Comment by yoavnir** [comment]
Hi.  I've created PR 19 with your changes on top of mine. Please look this over, and if it does contain your changes, I'll merge that and close this PR.
Thanks

**Pull request closed without merging**
